local_costmap:
  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.2
  static_map: false
  rolling_window: true
  resolution: 0.01
  # inflation_radius: 0.1
  width: 1.5
  height: 1.5

  plugins:
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}

  # obstacle_layer:
  #   # observation_sources: fake_lidar
  #   # fake_lidar: {sensor_frame: lidar, data_type: PointCloud, topic: LaserScan, marking: true, clearing: true}
  #   observation_sources: laser_scan_sensor
  #   laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan, marking: true, clearing: true}


